name: JavaScript

on:
  push:
    branches: [ main ]
    paths:
      - 'js/**'
      - '.github/workflows/javascript.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'js/**'
      - '.github/workflows/javascript.yml'

defaults:
  run:
    working-directory: js

jobs:
  test:
    name: Node.js Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: js/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Lint
      run: npm run lint
      
    - name: Type check
      run: npm run typecheck
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
      
    - name: Run Playwright tests
      run: npm test
      env:
        CI: true
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-node-${{ matrix.node-version }}
        path: js/playwright-report/
        retention-days: 30