name: JavaScript

on:
  push:
    branches: [ main ]
    paths:
      - 'js/**'
      - '.github/workflows/javascript.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'js/**'
      - '.github/workflows/javascript.yml'

defaults:
  run:
    working-directory: js

jobs:
  test:
    name: Node.js Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: js/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Lint
      run: npm run lint
      
    - name: Type check
      run: npm run typecheck
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
      
    - name: Install display server dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
      
    - name: Run Playwright tests
      run: |
        echo "Running tests with xvfb-run"
        xvfb-run -a --server-args="-screen 0 1280x1024x24" npm test -- --reporter=line
      env:
        DNS: ${{ secrets.CLOUDFLARE_DNS }}
        ZONEID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        API: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-node-${{ matrix.node-version }}
        path: js/playwright-report/
        retention-days: 30
