name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Swift Tests
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: SwiftyLab/setup-swift@latest
    - name: Swift version
      run: swift --version
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
      env:
        DNS: ${{ secrets.CLOUDFLARE_DNS }}
        ZONEID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        API: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint lint --strict
