name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Swift Tests
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "6.0"
    - name: Swift version
      run: swift --version
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
      
    - name: Build
      run: npm run build:swift
      
    - name: Run tests
      run: npm run test:swift
      env:
        DNS: ${{ secrets.CLOUDFLARE_DNS }}
        ZONEID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        API: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: npm run lint:swift
